// Client for Granola's official Business/Enterprise REST API.
// Spec: https://docs.granola.ai/api-reference/openapi.json
//
// Auth: Bearer token = a Granola API key (`grn_*`), generated by a
// Business/Enterprise user in Granola's settings. NOT the same as the
// desktop WorkOS access token.
//
// This is the API-only code path. It bypasses the local cache entirely
// and works on any machine with network + an API key. Used when:
//   • the local cache is encrypted (cache-v6+)
//   • the user prefers it (set GRANOLA_API_KEY or pass --granola-api-key)
//   • CI / non-Mac runs

const BASE = "https://public-api.granola.ai";

export type OfficialUser = {
  name: string | null;
  email: string;
};

export type OfficialFolder = {
  id: string;
  object: "folder";
  name: string;
  parent_folder_id: string | null;
};

export type OfficialSpeaker = {
  source: "microphone" | "speaker";
  diarization_label?: string;
};

export type OfficialTranscriptSegment = {
  speaker: OfficialSpeaker;
  text: string;
  start_time: string;
  end_time: string;
};

export type OfficialCalendarInvitee = { email: string };

export type OfficialCalendarEvent = {
  event_title: string | null;
  invitees: OfficialCalendarInvitee[];
  organiser: string | null;
  calendar_event_id: string | null;
  scheduled_start_time: string | null;
  scheduled_end_time: string | null;
};

export type OfficialNoteSummary = {
  id: string;
  object: "note";
  title: string | null;
  owner: OfficialUser;
  created_at: string;
  updated_at: string;
};

export type OfficialNoteDetail = OfficialNoteSummary & {
  web_url: string;
  calendar_event: OfficialCalendarEvent | null;
  attendees: OfficialUser[];
  folder_membership: OfficialFolder[];
  summary_text: string;
  summary_markdown: string | null;
  transcript: OfficialTranscriptSegment[] | null;
};

export type ListNotesResponse = {
  notes: OfficialNoteSummary[];
  hasMore: boolean;
  cursor: string | null;
};

export type ListFoldersResponse = {
  folders: OfficialFolder[];
  hasMore: boolean;
  cursor: string | null;
};

type FetchLike = (input: string, init: RequestInit) => Promise<Response>;

type RetryOpts = {
  attempts: number;
  baseDelayMs: number;
};

class TokenBucket {
  private tokens: number;
  private last: number;
  constructor(
    private readonly tokensPerSec: number,
    private readonly burst: number
  ) {
    this.tokens = burst;
    this.last = Date.now();
  }
  async take(): Promise<void> {
    while (true) {
      const now = Date.now();
      const elapsed = (now - this.last) / 1000;
      this.last = now;
      this.tokens = Math.min(
        this.burst,
        this.tokens + elapsed * this.tokensPerSec
      );
      if (this.tokens >= 1) {
        this.tokens -= 1;
        return;
      }
      const waitMs = ((1 - this.tokens) / this.tokensPerSec) * 1000;
      await new Promise((r) => setTimeout(r, Math.ceil(waitMs)));
    }
  }
}

export class OfficialGranolaApiError extends Error {
  constructor(
    message: string,
    public readonly status: number
  ) {
    super(message);
    this.name = "OfficialGranolaApiError";
  }
}

export type OfficialGranolaApiClientOpts = {
  fetch?: FetchLike;
  rateLimitTokensPerSec?: number;
  rateLimitBurst?: number;
  retry?: Partial<RetryOpts>;
};

export class OfficialGranolaApiClient {
  private fetch: FetchLike;
  private bucket: TokenBucket;
  private retryOpts: RetryOpts;

  constructor(
    private apiKey: string,
    opts: OfficialGranolaApiClientOpts = {}
  ) {
    this.fetch = opts.fetch ?? (globalThis.fetch as FetchLike);
    this.bucket = new TokenBucket(
      opts.rateLimitTokensPerSec ?? 5,
      opts.rateLimitBurst ?? 25
    );
    this.retryOpts = {
      attempts: opts.retry?.attempts ?? 3,
      baseDelayMs: opts.retry?.baseDelayMs ?? 250,
    };
  }

  /**
   * List all the user's notes via cursor pagination. Yields summaries
   * (no transcript). Use `getNote` for full content per id.
   */
  async *listAllNotes(opts?: {
    pageSize?: number;
    createdAfter?: string;
    updatedAfter?: string;
  }): AsyncGenerator<OfficialNoteSummary> {
    let cursor: string | null = null;
    while (true) {
      const params = new URLSearchParams();
      params.set("page_size", String(opts?.pageSize ?? 30));
      if (opts?.createdAfter) params.set("created_after", opts.createdAfter);
      if (opts?.updatedAfter) params.set("updated_after", opts.updatedAfter);
      if (cursor) params.set("cursor", cursor);
      const page = await this.get<ListNotesResponse>(
        `/v1/notes?${params.toString()}`
      );
      for (const n of page.notes) yield n;
      if (!page.hasMore || !page.cursor) return;
      cursor = page.cursor;
    }
  }

  async getNote(
    id: string,
    opts?: { includeTranscript?: boolean }
  ): Promise<OfficialNoteDetail> {
    const params = new URLSearchParams();
    if (opts?.includeTranscript) params.set("include", "transcript");
    const path =
      params.size > 0
        ? `/v1/notes/${id}?${params.toString()}`
        : `/v1/notes/${id}`;
    return this.get<OfficialNoteDetail>(path);
  }

  async *listAllFolders(): AsyncGenerator<OfficialFolder> {
    let cursor: string | null = null;
    while (true) {
      const params = new URLSearchParams({ page_size: "30" });
      if (cursor) params.set("cursor", cursor);
      const page = await this.get<ListFoldersResponse>(
        `/v1/folders?${params.toString()}`
      );
      for (const f of page.folders) yield f;
      if (!page.hasMore || !page.cursor) return;
      cursor = page.cursor;
    }
  }

  private async get<T>(path: string): Promise<T> {
    let lastErr: unknown = null;
    for (let i = 0; i < this.retryOpts.attempts; i++) {
      await this.bucket.take();
      const res = await this.fetch(`${BASE}${path}`, {
        method: "GET",
        headers: {
          accept: "application/json",
          authorization: `Bearer ${this.apiKey}`,
        },
      });
      if (res.ok) return (await res.json()) as T;
      const transient = res.status === 429 || res.status >= 500;
      const body = await res.text().catch(() => "");
      lastErr = new OfficialGranolaApiError(
        `Granola ${path} failed (${res.status}): ${body.slice(0, 200)}`,
        res.status
      );
      if (!transient) throw lastErr;
      const delay = this.retryOpts.baseDelayMs * Math.pow(4, i);
      await new Promise((r) => setTimeout(r, delay));
    }
    throw lastErr;
  }
}
